Commented out instanciation of Quartz scheduler for now because of hidden runtime dependencies (java.lang.NoClassDefFoundError: javax/transaction/UserTransaction) which are not part of some buildscripts.
git-svn-id: http://www.molgenis.org/svn/molgenis/trunk@10788 42de9c89-b41c-0410-9fa9-f33e7b6bda7a